/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type AddMutation = {
    addWorkspace: {
        __typename: "WorkspaceAddedResult" | "NotPermittedResult" | "WorkspaceExistsResult";
    } & (({
        workspace: {
            name: string;
        };
    }));
};
export type AddMutationVariables = {
    workspaceAddress: string;
    author: ({
        address: string;
        secret: string;
    }) | null;
};
