/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type IngestMutation = {
    ingestDocuments: {
        __typename: "WorkspaceNotFoundError" | "DocumentIngestionReport";
    } & ({
        __typename: "WorkspaceNotFoundError" | "DocumentIngestionReport";
    } & (({
        acceptedCount: number;
        ignoredCount: number;
        rejectedCount: number;
    })));
};
export type IngestMutationVariables = {
    workspace: string;
    documents: ({
        format: string;
        workspace: string;
        content: string;
        contentHash: string;
        path: string;
        author: string;
        timestamp: number;
        signature: string;
        deleteAfter: number | null;
    })[];
};
