/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type IngestMutation = {
    ingestDocuments: {
        __typename: "WorkspaceNotFoundError" | "IngestDocumentsSuccess";
    } & (({
        workspace: {
            documents: ((({
                contentHash: string;
            })))[];
        };
    }));
};
export type IngestMutationVariables = {
    workspace: string;
    documents: ({
        format: string;
        workspace: string;
        content: string;
        path: string;
        author: string;
        timestamp: number;
        signature: string;
        deleteAfter: number | null;
    })[];
};
