/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type LongNameQuery = {
    authors: ({
        longName: string | null;
    })[];
    workspaces: ({
        authors: ({
            longName: string | null;
        })[];
    })[];
};
export type LongNameQueryVariables = {};
