/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type RemoveMutation = {
    removeWorkspace: {
        __typename: "WorkspaceRemovedResult" | "NotPermittedResult";
    } & (({
        address: string;
    }));
};
export type RemoveMutationVariables = {
    workspaceAddress: string;
    author: ({
        address: string;
        secret: string;
    }) | null;
};
