/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type TestMutation = {
    set: {
        __typename: "SetDataSuccessResult" | "DocumentRejectedError" | "WorkspaceNotFoundError";
    };
};
export type TestMutationVariables = {
    author: {
        address: string;
        secret: string;
    };
    document: {
        format: ("ES4") | null;
        content: string;
        path: string;
        deleteAfter: number | null;
    };
    workspace: string;
};
