/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type TestQuery = {
    workspaces: ({
        address: string;
        name: string;
    })[];
};
export type TestQueryVariables = {};
